version: '3'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8081:80'
    environment:
      - PHP_ENABLE_XDEBUG=1

  mysql:
    image: mysql:5.7
    ports:
      - '3386:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=yii2basic
      - MYSQL_USER=yii2basic
      - MYSQL_PASSWORD=secret
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  mysql_test:
    image: mysql:5.7
    ports:
      - '33861:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=yii2_basic_tests
      - MYSQL_USER=yii2basic
      - MYSQL_PASSWORD=secret
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8888:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    depends_on:
      - mysql

  selenium:
    image: selenium/standalone-firefox:2.53.0
    ports:
      - '4444:4444'
